#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential'
cookbook 'apt'
cookbook 'vim'
cookbook 'git'
cookbook 'haskell', :git => 'https://github.com/michaelklishin/haskell-platform-chef-cookbook.git'
